# Generated by Django 6.0.5 on 2026-05-21 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('data_pairs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('template', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model'], name='api_promptv_model_748177_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mean_score', models.FloatField(blank=True, null=True)),
                ('pass_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='api.dataset')),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='api.promptversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('input_variables', models.JSONField(default=dict)),
                ('output', models.TextField(blank=True)),
                ('latency_ms', models.FloatField()),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='api.promptversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inputs', models.JSONField(default=dict)),
                ('output', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('score_details', models.JSONField(default=dict)),
                ('is_pass', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.evalrun')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_results', to='api.trace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['prompt_version', 'created_at'], name='api_trace_prompt__74f72f_idx'),
        ),
    ]
