# Generated by Django 5.2.14 on 2026-05-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('trace_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(db_index=True, default='RUNNING', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('span_count', models.IntegerField(default=0)),
                ('failed_span_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['agent_name', 'status'], name='api_agentru_agent_n_38f0f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('span_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('parent_span_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('agent_name', models.CharField(db_index=True, max_length=200)),
                ('action_type', models.CharField(default='observe', max_length=50)),
                ('tool_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(db_index=True, default='SUCCESS', max_length=50)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('input_data', models.JSONField(default=dict)),
                ('output', models.TextField(blank=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='api.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['agent_run', 'created_at'], name='api_span_agent_r_7fc11c_idx'), models.Index(fields=['status', 'agent_name'], name='api_span_status_0f3cee_idx')],
            },
        ),
    ]
