# Generated by Django 5.2.14 on 2026-07-20 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agentalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMetricRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, max_length=200)),
                ('hour', models.DateTimeField(db_index=True)),
                ('span_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-hour'],
            },
        ),
        migrations.CreateModel(
            name='SDKApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(db_index=True, max_length=12, unique=True)),
                ('key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['-started_at', 'agent_name'], name='idx_run_started_agent'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', '-started_at'], name='idx_run_status_started'),
        ),
        migrations.AddIndex(
            model_name='span',
            index=models.Index(fields=['-created_at', 'status'], name='idx_span_created_status'),
        ),
        migrations.AddIndex(
            model_name='span',
            index=models.Index(fields=['agent_name', '-created_at'], name='idx_span_agent_created'),
        ),
        migrations.AlterUniqueTogether(
            name='agentmetricrollup',
            unique_together={('agent_name', 'hour')},
        ),
    ]
